install:
	cp --force ./provenancelib.h /usr/local/include/provenancelib.h
	cp --force ./provenancefilter.h /usr/local/include/provenancefilter.h
	cp --force ./provenanceutils.h /usr/local/include/provenanceutils.h
	cp --force ./provenancePovJSON.h /usr/local/include/provenancePovJSON.h
